### ISSUE TITLE
ew AliDPG tags

### ISSUE THREAD

**Issue by fprino** [alisw/AliDPG#106]
Dear Dario, Giulio,

can you please create new tags for AliDPG on both the v5-09-XX and v5-08-XX branches.
This is to have new configurations for upcoming productions with injected nuclei and MC-to-MC embedding and two fixes for the merging of the output of AOD QA trains for both raw data and MC.

Thanks!

Cheers, Francesco

**Comment by dberzano** [comment]
Done.
