### ISSUE TITLE
Create a tag for v5-09-XX and v5-08-XX

### ISSUE THREAD

**Issue by chiarazampolli** [alisw/AliDPG#120]
Hello @ktf ,

As discussed, we need a new tag for AliDPG v5-08-XX (v5-08-XX-50) and v5-09-XX (v5-09-XX-40). In both cases, the ported commit is:

- change configuration for pi0 decays by Hijing 

Adding @catalinristea  and @fprino .

Thanks, and cheers,

Chiara

**Comment by ktf** [comment]
Done
