### ISSUE TITLE
New tag for v5-09-XX after merging it with master

### ISSUE THREAD

**Issue by chiarazampolli** [alisw/AliDPG#124]
Dear @ktf , @dberzano ,

Can you please create a new tag for v5-09-XX? Now the branch is merged to master. 

I am not listing here the changes wrt the last tag as they would be too many :) 

@catalinristea , @fprino , @germainma : do you prefer to start CPass tomorrow with the first beam with the new tag (if we have it), or with the old one? 

Note that I cannot add Elena, as I don't know her account. I will forward her the message.

Cheers,

Chiara

**Comment by catalinristea** [comment]
Ciao Chiara,

Thanks a lot for updating the v5-09-XX-branch. Let's use this new tag - we have tested before the reco with master AliDPG, I won't expect to have real issues if we do this.

Yours,
Catalin.

**Comment by dberzano** [comment]
Thanks Chiara for your efforts! Tagging now.

**Comment by chiarazampolli** [comment]
Ciao all,

Thanks! Let’s see what will happen:-)

Cheers,

Chiara


On 16 Apr 2018, at 15:51, Dario Berzano <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Chiara for your efforts! Tagging now.
