### ISSUE TITLE
New tag from v5-09-XX

### ISSUE THREAD

**Issue by chiarazampolli** [alisw/AliDPG#140]
Dear @dberzano , @ktf ,

Could you please make a new AliDPG tag from v5-09-XX? Here the changes wrt the last tag:

- Fix: use AliPIPEupgrade for Run3 
- Added Hyper-Helium-5 and Double-Hyper-Hydrogen-4 to the Generator_Nuclex 
- Custom generator for hijing + injected nuclei and hypernuclei for Run3 MC
- Fixed array size 
- CustomGenerators/Upgrade/Hijing_QED_Nuclex01.C, Updated bit mask for injection of all desired species
- switch from nightlies to official builds 
- Adapting QAtrainsim macro for ROOT6 
- Fix arguments of raw2clust 
- Use unified macro for AOD creation 
- update AOD_merge.C to match the one on alien 
- Use unified macro for AOD merging 
- Changing default to enable ESDtrackQA and set up PHOS QA task

Adding @miweberSMI , @catalinristea , @fprino .

Thanks!

Chiara

**Comment by chiarazampolli** [comment]
Hello,

Can you please wait before tagging? I tried to add a further commit, but it did not work... Let me have a look.

Cheers,

Chiara

**Comment by chiarazampolli** [comment]
Ok, done, I added one more commit, and you can tag.

Thanks!

Chiara

**Comment by dberzano** [comment]
Hi @chiarazampolli, @fprino, I don't see any of my commits ported to the v5-09-XX branch. Without those commits, we cannot use that AliDPG version for validation. Should I port them before tagging?

**Comment by dberzano** [comment]
We're talking #134, #138, #139.

**Comment by chiarazampolli** [comment]
You are absolutely right! Please, port them too.

Thanks,

Chiara

**Comment by chiarazampolli** [comment]
Hello,
The tag was done (v5-09-XX-46), closing.
Chiara
