### ISSUE TITLE
New tag from v5-09-XX 

### ISSUE THREAD

**Issue by chiarazampolli** [alisw/AliDPG#144]
Dear @dberzano , @ktf ,

We will need a new tag from v5-09-XX. I am currently waiting that Andreas confirms that the change in the default physics list for G4 is ok, then I will trigger you about it. 

Here the changes wrt to the latest tag (the last one was committed tonight - comment edited):

- Add method to check TObjArrays, needed for TRD QA output  
- Adapt the QED electrons min radius to low field 
- Use Nystrom stepper instead of default one for G4
- Added run number for CDB connect, needed by PCM task  
- Starlight configuration updated to increase the MC efficiency for the gamma-gamma process in the jpsi mass range
- Change phyics list to FTFP_INCLXX_EMV 
- Macros for production of HIJING with embedded PYTHIA HF-enriched signals 
- disable PWGHFvertexing in muon_calo passes

Adding @catalinristea , @fprino , @miweberSMI .

Chiara

**Comment by chiarazampolli** [comment]
Hello,

We decided to revert the commit about the Physics list for G4, for now. So here the changes:

- Add method to check TObjArrays, needed for TRD QA output  
- Adapt the QED electrons min radius to low field 
- Use Nystrom stepper instead of default one for G4
- Added run number for CDB connect, needed by PCM task  
- Starlight configuration updated to increase the MC efficiency for the gamma-gamma process in the jpsi mass range
- Change phyics list to FTFP_INCLXX_EMV 
- Macros for production of HIJING with embedded PYTHIA HF-enriched signals 
- disable PWGHFvertexing in muon_calo passes
- Revert "Change phyics list to FTFP_INCLXX_EMV"

@ktf , @dberzano , can you please tag?

Thanks, and cheers,

Chiara

**Comment by dberzano** [comment]
Hi all, @ktf's absent today - was this taken care of? Do you still need the tag?

**Comment by chiarazampolli** [comment]
Ciao Dario,
Yes, it was done. I will close the issue now.
Thanks,
Chiara
