### ISSUE TITLE
New tag for AliDPG v5-09-XX

### ISSUE THREAD

**Issue by chiarazampolli** [alisw/AliDPG#145]
Hello @ktf , @dberzano ,

Can you make a new tag from v5-09-XX? It will contain the following fixes:

-  Fixed string comparison 
- Revert "Revert "Change phyics list to FTFP_INCLXX_EMV""
- Removing path to AliDPG if we take the local macro 
- Possibility to use local macro in QA train for AOD 

Adding @fprino , @catalinristea , @miweberSMI .

This is needed for the FAST cycle of PPass of 18c.

Thanks!

Chiara

**Comment by ktf** [comment]
Build in progress.

**Comment by fprino** [comment]
Hi,

I guess this tag was created and it is v5-09-XX-48.
Right?

Ciao, Francesco

**Comment by dberzano** [comment]
Yes, @ktf took care of it :-)​

**Comment by fprino** [comment]
OK, I'll close it
