### ISSUE TITLE
New tag for AliDPG v5-09-XX

### ISSUE THREAD

**Issue by fprino** [alisw/AliDPG#148]
Dear Dario, Giulio,

can you please create a new AliDPG tag from v5-09-XX?
This is needed to have:
- a fix for the missing vertex task in the QA macro for simulations 
- new configurations for HF signals needed for upgrade simulations.

Thanks!

Best regards, Francesco

**Comment by miweberSMI** [comment]
Dear all,

we should probably add:
- bugfix DQ macro: Remove lines with pythia->SetStackFillOpt(AliGenPythia::kHeavyFlavor);
- bugfix LF macro: Inject 3He instead of 3H
When do you think we could ask to tag here?

Cheers,
Michael

**Comment by ktf** [comment]
Done. https://github.com/alisw/AliDPG/releases/tag/v5-09-XX-49

**Comment by chiarazampolli** [comment]
Super thanks!

Chiara
