### ISSUE TITLE
New tag for AliDPG v5-09-XX

### ISSUE THREAD

**Issue by miweberSMI** [alisw/AliDPG#152]
Dear @ktf , @dberzano, 

can you please create a new AliDPG tag from v5-09-XX?
This is needed to:
- discard the GRP written by AliSimulation in Run3 mode  
- avoid the redefinition of year in SimulationConfig.C 

Thanks and cheers,
Michael

**Comment by ktf** [comment]
ongoing...

**Comment by chiarazampolli** [comment]
Yes, it was done. 
@fprino , @miweberSMI , @catalinristea , next time I think we should put in the subject of the issue the name of the tag, so it is easier to see if it was done :) 

Cheers,

Chiara
