### ISSUE TITLE
Request new tag on v5-09-XX branch

### ISSUE THREAD

**Issue by fprino** [alisw/AliDPG#58]
We would like to have a new AliDPG tag to be used for:
- new refiltering of Pb-Pb MCs (AOD188) with some modifications in the gamma conversion AODs
- tests for the Xe-Xe simulation and reconstruction
The new features with respect to previous tag are:
- Xe-Xe case added in reconstruction scripts and QA and AOD macros 
- Xe-Xe case added in the MC configuration macros and scripts
- more robust treatment of the collision system in the delta AOD (HF and GA) creation 
- fix for PID response configuration in AOD creation for MCs

**Comment by dberzano** [comment]
Done, you'll receive an email when published!

https://github.com/alisw/AliDPG/releases/tag/v5-09-XX-25
