### ISSUE TITLE
Create new AliDPG tag on v5-09-XX

### ISSUE THREAD

**Issue by fprino** [alisw/AliDPG#65]
Dear Dario, Giulio,

this is to request a new AliDPG tag on the branch v5-09-XX, which is needed to have these featured in the next MC and raw data productions: 
* Disable muon refit in AOD refilterings
* QA of AODs
* Xe-Xe for STARLIGHT event generator
* bug fix in saving SPD tracklets in pp muon_calo productions

Thanks a lot!

Best regards, Francesco

**Comment by ktf** [comment]
Closed by https://github.com/alisw/AliDPG/releases/tag/v5-09-XX-27
