### ISSUE TITLE
Create new AliDPG tag on v5-08-XX branch

### ISSUE THREAD

**Issue by fprino** [alisw/AliDPG#66]
Hi,

this is to request a new AliDPG tag on the v5-08-XX branch, which is needed to have these features:
* disable muon refit in AOD refilterings
* New configuration for PWG-LF productions with injected resonances

Thanks!

Cheers, Francesco

**Comment by ktf** [comment]
Closed by https://github.com/alisw/AliDPG/releases/tag/v5-08-XX-39
