### ISSUE TITLE
Create new AliDPG tag on v5-09-XX branch

### ISSUE THREAD

**Issue by fprino** [alisw/AliDPG#70]
Hi Dario, Giulio,

can you please create a new tag on v5-09-XX branch of AliDPG.
This is needed for the processing of the forthcoming pp reference run and to be able to run the new performance generator in upcoming MC tests.
Here is a list of updates and fixes to keep track of the changes w.r.t. previous tag
- enable the statistics task in the AOD QA train
- updated muon configuration in QA train
- bug fix in CreateSnapshot macro
- performance generator
- fixed exit codes in TPCcalibration scripts

Thanks!

Best regards, Francesco

**Comment by dberzano** [comment]
Usual email will be received when published.
